version: '2'

services:

    http-proxy:
        image: nginx
        volumes:
            -
                type: bind
                source: ./http-proxy/default-vhost.conf
                target: /etc/nginx/conf.d/default.conf